openapi: 3.2.0
info:
  title: Taxonomy Options V1 API
  version: '1.0'
tags:
- name: Options V1
paths:
  /api/1/taxonomy/metaproperties/{metapropertyId}/options:
    get:
      tags:
      - Options V1
      operationId: getApi1TaxonomyMetapropertiesMetapropertyidOptions
      parameters:
      - name: metapropertyId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        required: false
        schema:
          type: string
      - name: before
        in: query
        required: false
        schema:
          type: string
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      - name: externalReference
        in: query
        required: false
        schema:
          type: string
          default: ''
      - name: ids
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOptionsOutput'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptionListInvalidOutput'
              examples:
                OptionListCursorParameterInvalidOutput:
                  summary: Response when the cursor parameters for listing options are invalid. 'start' and 'before' cannot be used together.
                  value:
                    errorCode: option-list-cursor-parameter-invalid
                    message: Invalid parameters provided for listing options with cursor pagination, 'start' and 'before' cannot be used together
                OptionListCursorFormatInvalidOutput:
                  summary: Response when the cursor format for listing options is invalid. Expected 'name_optionId'.
                  value:
                    errorCode: option-list-cursor-format-invalid
                    message: Invalid cursor format, expected 'name_optionId'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetapropertyNotExistingOutput1'
              examples:
                MetapropertyNotExisting:
                  summary: Response when the metaproperty does not exist
                  value:
                    errorCode: metaproperty-not-existing
                    message: Metaproperty does not exist
components:
  schemas:
    OptionListCursorFormatInvalidOutput:
      type: object
      required:
      - errorCode
      - message
      properties:
        errorCode:
          type: string
        message:
          type: string
    OptionListCursorParameterInvalidOutput:
      type: object
      required:
      - errorCode
      - message
      properties:
        errorCode:
          type: string
        message:
          type: string
    ListOptionsOutput:
      type: object
      required:
      - metadata
      - options
      properties:
        options:
          type: array
          items:
            $ref: '#/components/schemas/MetapropertyOption'
        metadata:
          $ref: '#/components/schemas/MetadataOutput'
    MetapropertyOption:
      type: object
      required:
      - id
      - name
      - externalReference
      - icon
      - metapropertyId
      properties:
        id:
          type: string
        name:
          type: string
        externalReference:
          type: string
        icon:
          type: string
        metapropertyId:
          type: string
    MetadataOutput:
      type: object
      properties:
        prevPage:
          type: string
        nextPage:
          type: string
    MetapropertyNotExistingOutput1:
      type: object
      required:
      - errorCode
      - message
      properties:
        errorCode:
          type: string
        message:
          type: string
    OptionListInvalidOutput:
      type: object
      oneOf:
      - $ref: '#/components/schemas/OptionListCursorFormatInvalidOutput'
      - $ref: '#/components/schemas/OptionListCursorParameterInvalidOutput'
