openapi: 3.2.0
info:
  title: Antivirus Quarantine API
  version: 1.0.0
servers:
- url: https://{your-bynder-domain}
tags:
- name: Quarantine
  description: ''
paths:
  /v7/quarantine/v1/assets:
    get:
      summary: Retrieve a list of quarantined assets
      tags:
      - Quarantine
      security:
      - OAuth2:
        - Audit quarantined assets
      - permanentToken:
        - Audit quarantined assets
      responses:
        '200':
          description: List of quarantined assets
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalCount:
                    type: integer
                    example: 1
                  assets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: a69f3104-0107-48af-a522-b437cd700b34
                        accountId:
                          type: string
                          example: 9c06c1e3-f0cb-427a-88f0-a545c475047f
                        assetId:
                          type: string
                          example: 5c554910-11f4-49a3-b7bf-04c21c99af05
                        assetName:
                          type: string
                          example: example-asset-name
                        requesterId:
                          type: string
                          example: 0b403671-8047-4fb9-9c59-ab4273973fb5
                        scanStatus:
                          type: string
                          enum:
                          - PENDING
                          - CLEARED
                          - INFECTED
                          - SKIPPED
                          example: SKIPPED
                        dateAdded:
                          type: string
                          format: date-time
                          example: '2024-06-28T10:42:02'
                        dateModified:
                          type: string
                          format: date-time
                          example: '2024-06-28T10:42:11'
                        uploadEventType:
                          type: string
                          example: LEGACY
                        fileType:
                          type: string
                          example: None
                        fileSize:
                          type: integer
                          example: 0
                        scanFailureReason:
                          type: string
                          example: client_error
                        reviewStatus:
                          type: string
                          enum:
                          - APPROVED
                          - REJECTED
                          example: null
                        reviewedById:
                          type: string
                          example: null
                        isRemoved:
                          type: boolean
                          example: false
                        isSafe:
                          type: boolean
                          example: false
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Asset not found
  /v7/quarantine/v1/assets/{asset_id}:
    get:
      summary: Retrieve a quarantined asset by id
      tags:
      - Quarantine
      security:
      - OAuth2:
        - Audit quarantined assets
      - permanentToken:
        - Audit quarantined assets
      parameters:
      - name: asset_id
        in: path
        required: true
        schema:
          type: string
          example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Quarantined asset details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: a69f3104-0107-48af-a522-b437cd700b34
                  accountId:
                    type: string
                    example: 9c06c1e3-f0cb-427a-88f0-a545c475047f
                  assetId:
                    type: string
                    example: 5c554910-11f4-49a3-b7bf-04c21c99af05
                  assetName:
                    type: string
                    example: example-asset-name
                  requesterId:
                    type: string
                    example: 0b403671-8047-4fb9-9c59-ab4273973fb5
                  scanStatus:
                    type: string
                    enum:
                    - PENDING
                    - CLEARED
                    - INFECTED
                    - SKIPPED
                    example: SKIPPED
                  dateAdded:
                    type: string
                    format: date-time
                    example: '2024-06-28T10:42:02'
                  dateModified:
                    type: string
                    format: date-time
                    example: '2024-06-28T10:42:11'
                  uploadEventType:
                    type: string
                    example: LEGACY
                  fileType:
                    type: string
                    example: None
                  fileSize:
                    type: integer
                    example: 0
                  scanFailureReason:
                    type: string
                    example: client_error
                  reviewStatus:
                    type: string
                    enum:
                    - APPROVED
                    - REJECTED
                    example: null
                  reviewedById:
                    type: string
                    example: null
                  isRemoved:
                    type: boolean
                    example: false
                  isSafe:
                    type: boolean
                    example: false
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Asset not found
    put:
      summary: Update review status by id
      tags:
      - Quarantine
      security:
      - OAuth2:
        - Audit quarantined assets
      - permanentToken:
        - Audit quarantined assets
      parameters:
      - name: asset_id
        in: path
        required: true
        schema:
          type: string
          example: 00000000-0000-0000-0000-000000000000
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    review_status:
                      type: string
                      enum:
                      - APPROVED
                      - DENIED
                      example: DENIED
      responses:
        '200':
          description: Review status updated
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Asset not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Asset not found
  /v7/quarantine/v1/antivirus-audit:
    post:
      summary: Update review status by list of asset Ids
      tags:
      - Quarantine
      security:
      - OAuth2:
        - Audit quarantined assets
      - permanentToken:
        - Audit quarantined assets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    antivirus_asset_ids:
                      type: array
                      items:
                        type: string
                        example: ac93e443-e4d5-442f-966b-b6f24c025c71
                    review_status:
                      type: string
                      enum:
                      - APPROVED
                      - DENIED
                      example: DENIED
      responses:
        '200':
          description: Review status updated
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    permanentToken:
      type: apiKey
      in: header
      name: Authorization
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            Audit quarantined assets: ''
        authorizationCode:
          authorizationUrl: https://{your-auth-url}
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            Audit quarantined assets: ''
