openapi: 3.2.0
info:
  title: automation-workflow-svc Automation Workflow Conditions API
  version: 1.0.0
  description: 'This API enables clients to manage automation-workflow rules.

    **Servers:**

    1. **Local Development:**

    - Base URL: `http://localhost:8080/{endpoint}`


    2. **Stage or Production:**

    - Base URL: `https://automation-workflow-service.bynder.com/api/1/automation-workflow/{endpoint}`


    Ensure you are using the appropriate server based on your environment (local or production).'
tags:
- name: Automation Workflow Conditions
paths:
  /conditions:
    get:
      tags:
      - Automation Workflow Conditions
      summary: List Automation Workflow Conditions
      description: Get a list of available automation workflow conditions.
      operationId: getConditions
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomationWorkflowConditionsResponse'
              example:
                conditions:
                - name: AssetType
                  operators:
                  - CONTAINS
                  - DOES_NOT_CONTAIN
                  terms:
                  - IMAGE
                  - VIDEO
                  - DOCUMENT
                  - AUDIO
                  - 3D
                - name: Metaproperty
                  operators:
                  - CONTAINS
                  - DOES_NOT_CONTAIN
                  terms:
                  - 00000000-0000-0000-0000-000000000000
                  - 00000000-0000-0000-0000-000000000000
                maxConditionsCount: 5
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
      security:
      - {}
      - httpAuth: []
components:
  schemas:
    AutomationWorkflowCondition:
      title: AutomationWorkflowCondition
      type: object
      required:
      - name
      - weight
      properties:
        name:
          type: string
        weight:
          type: integer
          format: int32
        operators:
          type: array
          items:
            type: string
        terms:
          type: array
          items:
            type: string
    AutomationWorkflowConditionsResponse:
      title: AutomationWorkflowConditionsResponse
      type: object
      required:
      - maxConditionsCount
      properties:
        conditions:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowCondition'
        maxConditionsCount:
          type: integer
          format: int32
    ErrorResponse:
      title: ErrorResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
    ErrorAuthorizationResponse:
      title: ErrorAuthorizationResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
