openapi: 3.2.0
info:
  title: automation-workflow-svc Automation Workflow Triggers API
  version: 1.0.0
  description: 'This API enables clients to manage automation-workflow rules.

    **Servers:**

    1. **Local Development:**

    - Base URL: `http://localhost:8080/{endpoint}`


    2. **Stage or Production:**

    - Base URL: `https://automation-workflow-service.bynder.com/api/1/automation-workflow/{endpoint}`


    Ensure you are using the appropriate server based on your environment (local or production).'
tags:
- name: Automation Workflow Triggers
paths:
  /triggers:
    get:
      tags:
      - Automation Workflow Triggers
      summary: List Automation Workflow Triggers
      description: Get a list of available automation workflow triggers.
      operationId: getTriggers
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomationWorkflowTriggersResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
      security:
      - {}
      - httpAuth: []
components:
  schemas:
    AutomationWorkflowTriggersResponse:
      title: AutomationWorkflowTriggersResponse
      type: object
      properties:
        triggers:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowTrigger'
    ErrorAuthorizationResponse:
      title: ErrorAuthorizationResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
    AutomationWorkflowTrigger:
      title: AutomationWorkflowTrigger
      type: object
      required:
      - name
      properties:
        name:
          type: string
    ErrorResponse:
      title: ErrorResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
