openapi: 3.2.0
info:
  title: Webhooks Configurations API
  contact: {}
  version: 1.0.0
servers:
- url: https://{your-bynder-domain}/
  variables:
    your-bynder-domain:
      default: your-bynder-domainDefaultValue
tags:
- name: Configurations
  description: ''
paths:
  /v7/webhooks/public/api/subscriptions/{id}:
    parameters: []
    get:
      summary: Retrieve a Webhook Configuration
      description: Please be aware that using this endpoint requires either the `View Webhooks configurations` or `Manage Webhooks configurations` security role.
      tags:
      - Configurations
      operationId: RetrieveaWebhookConfiguration
      parameters:
      - name: id
        in: path
        description: Webhook configuration ID.
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV7WebhooksPublicApiSubscriptionsResponse'
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                type: object
      deprecated: false
    post:
      summary: Create a Webhook Configuration
      description: Please be aware that using this endpoint requires the `Manage Webhooks configurations` security role.
      tags:
      - Configurations
      operationId: CreateaWebhookConfiguration
      parameters:
      - name: id
        in: path
        description: Webhook configuration ID.
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiV7WebhooksPublicApiSubscriptionsRequest'
        required: true
      responses:
        '201':
          description: Webhook created successfully
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV7WebhooksPublicApiSubscriptionsResponse'
      deprecated: false
    put:
      summary: Update a Webhook Configuration
      description: Please be aware that using this endpoint requires the `Manage Webhooks configurations` security role.
      tags:
      - Configurations
      operationId: UpdateaWebhookConfiguration
      parameters:
      - name: id
        in: path
        description: Webhook configuration ID.
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiV7WebhooksPublicApiSubscriptionsRequest1'
        required: true
      responses:
        '200':
          description: Webhook updated successfully
          headers: {}
          content: {}
      deprecated: false
    patch:
      summary: Patch a Webhook Configuration
      description: Please be aware that using this endpoint requires the `Manage Webhooks configurations` security role.
      tags:
      - Configurations
      operationId: PatchaWebhookConfiguration
      parameters:
      - name: id
        in: path
        description: Webhook configuration ID.
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiV7WebhooksPublicApiSubscriptionsRequest2'
        required: true
      responses:
        '200':
          description: Webhook patched successfully
          headers: {}
          content: {}
      deprecated: false
    delete:
      summary: Delete a Webhook Configuration
      description: Please be aware that using this endpoint requires the `Manage Webhooks configurations` security role.
      tags:
      - Configurations
      operationId: DeleteaWebhookConfiguration
      parameters:
      - name: id
        in: path
        description: Webhook configuration ID.
        required: true
        style: simple
        schema:
          type: string
      responses:
        '204':
          description: Webhook deleted successfully
          headers: {}
          content: {}
      deprecated: false
components:
  schemas:
    ApiV7WebhooksPublicApiSubscriptionsResponse:
      title: ApiV7WebhooksPublicApiSubscriptionsResponse
      type: object
      properties:
        id:
          type: string
          examples:
          - 00000000-0000-0000-0000-000000000000
    ApiV7WebhooksPublicApiSubscriptionsRequest:
      title: ApiV7WebhooksPublicApiSubscriptionsRequest
      type: object
      properties:
        name:
          type: string
          examples:
          - NAME OF WEBHOOK
        endpoint:
          type: string
          examples:
          - ENDPOINT URL OR ARN OR EMAIL
        protocol:
          type: string
          examples:
          - PROTOCOL
        events:
          type: array
          items:
            type: string
          description: ''
        preArchivedNotificationDays:
          type: integer
          contentEncoding: int32
          examples:
          - 5
    ApiV7WebhooksPublicApiSubscriptionsRequest1:
      title: ApiV7WebhooksPublicApiSubscriptionsRequest1
      type: object
      properties:
        events:
          type: array
          items:
            type: string
          description: ''
        preArchivedNotificationDays:
          type: integer
          contentEncoding: int32
          examples:
          - 5
    ApiV7WebhooksPublicApiSubscriptionsRequest2:
      title: ApiV7WebhooksPublicApiSubscriptionsRequest2
      type: object
      properties:
        name:
          type: string
          examples:
          - Updated name via API
        status:
          type: integer
          contentEncoding: int32
          examples:
          - 1
