openapi: 3.2.0
info:
  title: Modern Stack File Upload Step 1 API
  version: 1.0.0
  description: This endpoint prepares the upload of a file in chunks. It returns a file ID that will be used in subsequent steps to upload the file chunks and finalize the upload.
servers:
- url: https://{your-bynder-domain}/
  variables:
    your-bynder-domain:
      default: example.com
      description: Your Bynder domain.
tags:
- name: Step 1
  description: This endpoint prepares the upload of a file in chunks. It returns a file ID that will be used in subsequent steps to upload the file chunks and finalize the upload.
paths:
  /v7/file_cmds/upload/prepare:
    post:
      summary: Prepare the upload
      description: Prepare the upload of a file in chunks.
      tags:
      - Step 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_id:
                    type: string
                    description: File ID to be used in subsequent upload steps.
                    example: 00000000-0000-0000-0000-000000000000
        '400':
          description: Bad request
      operationId: postV7FileCmdsUploadPrepare
      x-operation-id-source: derived
