openapi: 3.2.0
info:
  title: automation-workflow-svc Automation Workflow Rules API
  version: 1.0.0
  description: 'This API enables clients to manage automation-workflow rules.

    **Servers:**

    1. **Local Development:**

    - Base URL: `http://localhost:8080/{endpoint}`


    2. **Stage or Production:**

    - Base URL: `https://automation-workflow-service.bynder.com/api/1/automation-workflow/{endpoint}`


    Ensure you are using the appropriate server based on your environment (local or production).'
tags:
- name: Automation Workflow Rules
paths:
  /rules:
    get:
      tags:
      - Automation Workflow Rules
      summary: Fetches all automation workflow rules
      description: Get all automation workflow rules by account id, with optional pagination (start and limit).
      operationId: getRules
      parameters:
      - name: start
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAutomationWorkflowRulesResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
      security:
      - {}
      - httpAuth: []
    post:
      tags:
      - Automation Workflow Rules
      summary: Create Automation Workflow Rule
      description: Create a new automation workflow rule.
      operationId: postRules
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutomationWorkflowRuleBody'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAutomationWorkflowRuleResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
      security:
      - {}
      - httpAuth: []
  /rules/{ruleId}:
    get:
      tags:
      - Automation Workflow Rules
      summary: Fetches a automation workflow rule
      description: Get a automation workflow rule by account id
      operationId: getRulesRuleid
      parameters:
      - name: ruleId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleRuleAutomationWorkflowResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNotFound'
      security:
      - {}
      - httpAuth: []
    put:
      tags:
      - Automation Workflow Rules
      summary: Edit Automation Workflow Rule
      description: Edit an existing automation workflow rule.
      operationId: putRulesRuleid
      parameters:
      - name: ruleId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditAutomationWorkflowRuleBody'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleRuleAutomationWorkflowResponse'
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNotFound'
      security:
      - {}
      - httpAuth: []
    delete:
      tags:
      - Automation Workflow Rules
      summary: Remove Automation Workflow Rule
      description: Remove an automation workflow rule by its ID.
      operationId: deleteRulesRuleid
      parameters:
      - name: ruleId
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: ''
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNotFound'
      security:
      - {}
      - httpAuth: []
  /rules/{ruleId}/status:
    patch:
      tags:
      - Automation Workflow Rules
      summary: Update Automation Workflow Rule Status
      description: Update the status of an existing automation workflow rule.
      operationId: patchRulesRuleidStatus
      parameters:
      - name: ruleId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusAutomationWorkflowRuleBody'
        required: true
      responses:
        '204':
          description: ''
        '400':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorAuthorizationResponse'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseNotFound'
        '409':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseRuleAlreadyPaused'
      security:
      - {}
      - httpAuth: []
components:
  schemas:
    LeafCondition:
      title: LeafCondition
      type: object
      required:
      - condition_type
      - expression
      properties:
        condition_type:
          type: string
        expression:
          $ref: '#/components/schemas/ExpressionCondition'
    ErrorResponse:
      title: ErrorResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
    AndCondition:
      title: AndCondition
      type: object
      properties:
        AND:
          type: array
          items:
            $ref: '#/components/schemas/LeafCondition'
    ExpressionCondition:
      title: ExpressionCondition
      type: object
      required:
      - operator
      properties:
        term:
          type: array
          items:
            type: string
        operator:
          type: string
    MetadataOutput:
      title: MetadataOutput
      type: object
      properties:
        previousPage:
          type: string
        nextPage:
          type: string
    AutomationWorkflowStepActionAgent:
      title: AutomationWorkflowStepActionAgent
      type: object
      required:
      - action_type
      - data
      properties:
        action_type:
          type: string
        data:
          $ref: '#/components/schemas/StepActionAgentData'
    AutomationWorkflowStepActionBase:
      title: AutomationWorkflowStepActionBase
      oneOf:
      - $ref: '#/components/schemas/AutomationWorkflowStepActionAgent'
    StepActionAgentData:
      title: StepActionAgentData
      type: object
      required:
      - agentId
      properties:
        agentId:
          type: string
    ErrorAuthorizationResponse:
      title: ErrorAuthorizationResponse
      type: object
      required:
      - message
      properties:
        message:
          type: string
    CreateAutomationWorkflowRuleResponse:
      title: CreateAutomationWorkflowRuleResponse
      type: object
      required:
      - id
      - status
      - name
      - accountId
      - createdById
      - dateCreated
      - dateModified
      properties:
        id:
          type: string
        status:
          type: string
        name:
          type: string
        accountId:
          type: string
        createdById:
          type: string
        editedById:
          type: string
        dateCreated:
          type: string
        dateModified:
          type: string
    SingleRuleAutomationWorkflowResponse:
      title: SingleRuleAutomationWorkflowResponse
      type: object
      required:
      - id
      - status
      - name
      - dateCreated
      - createdById
      - dateModified
      properties:
        id:
          type: string
        status:
          type: string
        name:
          type: string
        dateCreated:
          type: string
        createdById:
          type: string
        dateModified:
          type: string
        editedById:
          type: string
        dateRemoved:
          type: string
        triggers:
          type: array
          items:
            type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowStep'
    ErrorResponseNotFound:
      title: ErrorResponseNotFound
      type: object
      required:
      - message
      properties:
        message:
          type: string
    EditAutomationWorkflowRuleBody:
      title: EditAutomationWorkflowRuleBody
      type: object
      properties:
        name:
          type: string
        triggers:
          type: array
          items:
            type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowStep'
    AutomationWorkflowResponse:
      title: AutomationWorkflowResponse
      type: object
      required:
      - id
      - status
      - name
      - createdById
      - dateCreated
      properties:
        id:
          type: string
        status:
          type: string
        name:
          type: string
        createdById:
          type: string
        dateCreated:
          type: string
        triggers:
          type: array
          items:
            type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowStep'
    ListAutomationWorkflowRulesResponse:
      title: ListAutomationWorkflowRulesResponse
      type: object
      required:
      - metadata
      properties:
        rules:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowResponse'
        metadata:
          $ref: '#/components/schemas/MetadataOutput'
    AutomationWorkflowRuleBody:
      title: AutomationWorkflowRuleBody
      type: object
      required:
      - name
      properties:
        name:
          type: string
        triggers:
          type: array
          items:
            type: string
        steps:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowStep'
    UpdateStatusAutomationWorkflowRuleBody:
      title: UpdateStatusAutomationWorkflowRuleBody
      type: object
      required:
      - status
      properties:
        status:
          type: string
    AutomationWorkflowStep:
      title: AutomationWorkflowStep
      type: object
      properties:
        step_triggers:
          type: array
          items:
            type: string
        actions:
          type: array
          items:
            $ref: '#/components/schemas/AutomationWorkflowStepActionBase'
        conditions:
          type: array
          items:
            $ref: '#/components/schemas/AndCondition'
    ErrorResponseRuleAlreadyPaused:
      title: ErrorResponseRuleAlreadyPaused
      type: object
      required:
      - message
      properties:
        message:
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
