openapi: 3.2.0
info:
  title: Modern Stack File Upload Step 3 API
  version: 1.0.0
  description: This endpoint finalizes the upload after all chunks have been uploaded. You need to provide the file ID and details about the file, including its name, size, and the number of chunks it was split into.
servers:
- url: https://{your-bynder-domain}/
  variables:
    your-bynder-domain:
      default: example.com
      description: Your Bynder domain.
tags:
- name: Step 3
  description: This endpoint finalizes the upload after all chunks have been uploaded. You need to provide the file ID and details about the file, including its name, size, and the number of chunks it was split into.
paths:
  /v7/file_cmds/upload/{file_id}/finalise_api:
    post:
      summary: Finalize the upload
      description: Finalize the upload after all chunks have been uploaded.
      tags:
      - Step 3
      parameters:
      - name: file_id
        in: path
        required: true
        description: The file ID retrieved from the prepare upload step.
        schema:
          type: string
          example: 00000000-0000-0000-0000-000000000000
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  description: Filename of the file.
                  example: image.jpeg
                fileSize:
                  type: integer
                  description: Size of the file in bytes.
                  example: 63973541
                chunksCount:
                  type: integer
                  description: Number of chunks the file was split into.
                  example: 1
      responses:
        '201':
          description: Upload finalized successfully
        '400':
          description: Bad request
      operationId: postV7FileCmdsUploadByFileIdFinaliseApi
      x-operation-id-source: derived
