openapi: 3.2.0
info:
  title: Analytics Collection Usage API
  version: 1.0.0
  description: 'These endpoints return information related to the specific event. You can enrich these events with specific data about the collection or the user by making use of the [Collections API endpoints](#reference/collections) or the [Users API endpoints](#reference/users).

    '
servers:
- url: https://{your-bynder-domain}
security:
- permanentToken:
  - analytics.api:read
- oauth2:
  - analytics.api:read
tags:
- name: Collection Usage
  description: 'These endpoints return information related to the specific event. You can enrich these events with specific data about the collection or the user by making use of the [Collections API endpoints](#reference/collections) or the [Users API endpoints](#reference/users).

    '
paths:
  /v7/analytics/api/v1/collection/views:
    get:
      summary: Retrieve collection view events
      tags:
      - Collection Usage
      parameters:
      - name: limit
        in: query
        description: The maximum number of analytics events to retrieve. Allowed values are between 1 and 10000.
        required: false
        schema:
          type: integer
          default: 1000
      - name: cursor
        in: query
        description: Cursor mark returned in the response headers to be used for pagination purposes.
        required: false
        schema:
          type: string
          default: MA
      - name: fromDateTime
        in: query
        description: 'Retrieve view events occurred after this date. ISO8601 format: yyyy-mm-ddThh:mm[:ssZ] with optional seconds.

          '
        required: false
        schema:
          type: string
          format: date-time
      - name: toDateTime
        in: query
        description: 'Set a date range together with the "fromDateTime" parameter. ISO8601 format: yyyy-mm-ddThh:mm[:ssZ] with optional seconds.

          '
        required: false
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successful response
          headers:
            Next-Cursor:
              description: The next cursor value to send if you want to continue with your paginated request.
              schema:
                type: string
            Next-Url:
              description: The next URL path to query if you want to continue with your paginated request.
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    eventId:
                      type: string
                      example: ad3c8d01-4a2f-461c-b17d-2ecc51723028
                    collectionId:
                      type: string
                      example: CA510292-E39E-4B28-AB6444CDD2B1C5C0
                    eventType:
                      type: string
                      example: CollectionViewed
                    dateTime:
                      type: string
                      format: date-time
                      example: '2021-11-15T10:07:57.781+00:00'
                    userId:
                      type: string
                      example: 1A84D758-2B3A-141F-8F07D71AA1F223BD
                    isOwner:
                      type: boolean
                      example: false
                    viewOrigin:
                      type: string
                      example: internal
                    ipAddress:
                      type: string
                      example: 192.158.1.38
                    userAgent:
                      type: string
                      example: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
                    isBynderSupport:
                      type: boolean
                      example: false
              examples:
                example-1:
                  summary: Example response
                  value: "[\n  {\n    \"eventId\": \"ad3c8d01-4a2f-461c-b17d-2ecc51723028\",\n    \"collectionId\": \"CA510292-E39E-4B28-AB6444CDD2B1C5C0\",\n    \"eventType\": \"CollectionViewed\",\n    \"dateTime\": \"2021-11-15T10:07:57.781+00:00\",\n    \"userId\": \"1A84D758-2B3A-141F-8F07D71AA1F223BD\",\n    \"isOwner\": false,\n    \"viewOrigin\": \"internal\",\n    \"ipAddress\": \"192.158.1.38\",\n    \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\",\n    \"isBynderSupport\": false\n  },\n  {\n    \"eventId\": \"ad3c8d01-4a2f-461c-b17d-2ecc51723028\",\n    \"collectionId\": \"CA510292-E39E-4B28-AB6444CDD2B1C5C0\",\n    \"eventType\": \"CollectionViewed\",\n    \"dateTime\": \"2021-11-15T10:07:57.781+00:00\",\n    \"userId\": \"\",\n    \"isOwner\": false,\n    \"viewOrigin\": \"embed\",\n    \"ipAddress\": \"192.158.1.38\",\n    \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36\",\n    \"isBynderSupport\": false\n  }\n]\n"
  /v7/analytics/api/v1/collection/views.csv:
    get:
      summary: Retrieve collection view events in CSV format
      tags:
      - Collection Usage
      parameters:
      - name: limit
        in: query
        description: The maximum number of analytics events to retrieve. Allowed values are between 1 and 10000.
        required: false
        schema:
          type: integer
          default: 1000
      - name: cursor
        in: query
        description: Cursor mark returned in the response headers to be used for pagination purposes.
        required: false
        schema:
          type: string
          default: MA
      - name: fromDateTime
        in: query
        description: 'Retrieve view events occurred after this date. ISO8601 format: yyyy-mm-ddThh:mm[:ssZ] with optional seconds.

          '
        required: false
        schema:
          type: string
          format: date-time
      - name: toDateTime
        in: query
        description: 'Set a date range together with the "fromDateTime" parameter. ISO8601 format: yyyy-mm-ddThh:mm[:ssZ] with optional seconds.

          '
        required: false
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successful response
          headers:
            Next-Cursor:
              description: The next cursor value to send if you want to continue with your paginated request.
              schema:
                type: string
            Next-Url:
              description: The next URL path to query if you want to continue with your paginated request.
              schema:
                type: string
          content:
            text/csv:
              examples:
                example-1:
                  summary: Example CSV response
                  value: 'eventId,collectionId,eventType,dateTime,userId,isOwner,viewOrigin,ipAddress,userAgent,isBynderSupport

                    "ad3c8d01-4a2f-461c-b17d-2ecc51723028", "CA510292-E39E-4B28-AB6444CDD2B1C5C0", CollectionViewed, 2021-11-15T10:07:57.781+00:00, 1A84D758-2B3A-141F-8F07D71AA1F223BD, false, internal, 192.158.1.38, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36", false

                    "ad3c8d01-4a2f-461c-b17d-2ecc51723028", "CA510292-E39E-4B28-AB6444CDD2B1C5C0", CollectionViewed, 2021-11-15T10:07:57.781+00:00,, false, embed, 192.158.1.38, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36", false

                    '
components:
  securitySchemes:
    permanentToken:
      type: apiKey
      in: header
      name: Authorization
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            analytics.api:read: ''
        authorizationCode:
          authorizationUrl: https://{your-auth-url}
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes:
            analytics.api:read: ''
