openapi: 3.2.0
info:
  title: Dynamic Asset Transformations Transform API
  version: 1.0.0
servers:
- url: https://{your-bynder-domain}/
security:
- OAuth2: []
- permanentToken: []
tags:
- name: Transform
paths:
  /transform/{id}/{name}:
    get:
      summary: Generate dynamic asset transformation
      description: 'Generate a derivative on the fly with a transformation (such as cropping, scaling, filling) applied to it.   More information about this feature can be found in our [Knowledge Base item](https://support.bynder.com/hc/en-us/articles/360018559260-Dynamic-Asset-Transformations-DAT-).

        Image operations can be passed as `io` parameters in the form of `transform:{operation},{param1}:{value1},{param2}:{value2},...`.   It''s possible to specify several operations: `?io={operation1}&io={operation2}&...`. The operations will be applied in the same order they are passed in the url.

        These are the possible image operations and their parameters:

        | Operation    | Parameter       | Possible values                                                                      | | ------------ | --------------- | ------------------------------------------------------------------------------------ | | `background` | color           | color name (yellow, black, etc.) or hexadecimal (rgb, rrggbb)                        | | `crop`       | width           | integer                                                                              | |              | height          | integer                                                                              | |              | x               | integer                                                                              | |              | y               | integer                                                                              | |              | gravity         | topleft / top / topright / left / center / right / bottomleft / bottom / bottomright | |              | shape           | circle / square                                                                      | |              | blur            | integer                                                                              | |              | background      | color name (yellow, black, etc.) or hexadecimal (rgb, rrggbb)                        | | `extend`     | width           | integer                                                                              | |              | height          | integer                                                                              | |              | background      | color name (yellow, black, etc.) or hexadecimal (rgb, rrggbb)                        | | `fill`       | width           | integer                                                                              | |              | height          | integer                                                                              | |              | gravity         | topleft / top / topright / left / center / right / bottomleft / bottom / bottomright | |              | aspectratio     | {integer}x{integer}                                                                  | | `fit`        | width           | integer                                                                              | |              | height          | integer                                                                              | | `flip`       | (no parameters) |                                                                                      | | `mirror`     | (no parameters) |                                                                                      | | `rotate`     | angle           | integer between 0 and 360                                                            | |              | background      | color name (yellow, black, etc.) or hexadecimal (rgb, rrggbb)                        | | `scale`      | width           | integer                                                                              | |              | height          | integer                                                                              |

        '
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: io
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
        description: The operation(s) performed on the image before it's served to the client.
      - name: focuspoint
        in: query
        required: false
        schema:
          type: string
        description: Focus point as a x,y coordinate (with values between 0 - 1).
      - name: format
        in: query
        required: false
        schema:
          type: string
        description: Format of the served image. This can either be `jpg` or `png` and it will overwrite the default `webP`.
      - name: quality
        in: query
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
        description: Image quality, ranging from 1 - 100 (has no effect when `format` is set to 'png').
      responses:
        '200':
          description: Image
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Image Operation not supported
        '404':
          description: Not Found
      tags:
      - Transform
components:
  securitySchemes:
    permanentToken:
      type: apiKey
      in: header
      name: Authorization
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://{your-auth-url}
          tokenUrl: https://{your-bynder-domain}/v6/authentication/oauth2/token
          scopes: {}
